part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const HOME = _Paths.HOME;
  static const ONBOARD = _Paths.ONBOARD;
  static const TERMSANDCONDITION = _Paths.TERMSANDCONDITION;
  static const SIGNIN = _Paths.SIGNIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const SENDOTP = _Paths.SENDOTP;
  static const VERIFYOTP = _Paths.VERIFYOTP;
  static const RESETPASSWORD = _Paths.RESETPASSWORD;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const ESSENTIAL_SERVICE = _Paths.ESSENTIAL_SERVICE;
  static const COMMUNITY = _Paths.COMMUNITY;
  static const LEARNARABIC = _Paths.LEARNARABIC;
  static const TOURIST_SPOT = _Paths.TOURIST_SPOT;
  static const BUSFLIGHT = _Paths.BUSFLIGHT;
  static const LOCALTOUR = _Paths.LOCALTOUR;
  static const BASICGOODS = _Paths.BASICGOODS;
  static const INFORMATIONS = _Paths.INFORMATIONS;
  static const EMBASSY = _Paths.EMBASSY;
  static const HOSPITALS = _Paths.HOSPITALS;
  static const RESTAURENTS = _Paths.RESTAURENTS;
  static const ARTICLES = _Paths.ARTICLES;
  static const PROFILE = _Paths.PROFILE;
  static const CREATEPOST = _Paths.CREATEPOST;
  static const EDITPROFILE = _Paths.EDITPROFILE;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const TERMSANDCONDITIONS = _Paths.TERMSANDCONDITIONS;
  static const HELP = _Paths.HELP;
  static const ABOUTUS = _Paths.ABOUTUS;
  static const LANGUAGE = _Paths.LANGUAGE;
  static const SHOP = _Paths.SHOP;
  static const PRODUCT_DETAILS = _Paths.PRODUCT_DETAILS;
  static const ALL_PRODUCTS = _Paths.ALL_PRODUCTS;
  static const ALL_CATEGORIES = _Paths.ALL_CATEGORIES;
  static const COMMUNITY_FEED = _Paths.COMMUNITY_FEED;
  static const NAMAJ = _Paths.NAMAJ;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const HOME = '/home';
  static const ONBOARD = '/onboard';
  static const TERMSANDCONDITION = '/termsandcondition';
  static const SIGNIN = '/signin';
  static const SIGNUP = '/signup';
  static const SENDOTP = '/sendotp';
  static const VERIFYOTP = '/verifyotp';
  static const RESETPASSWORD = '/resetpassword';
  static const DASHBOARD = '/dashboard';
  static const ESSENTIAL_SERVICE = '/essential-service';
  static const COMMUNITY = '/community';
  static const LEARNARABIC = '/learnarabic';
  static const TOURIST_SPOT = '/tourist-spot';
  static const BUSFLIGHT = '/busflight';
  static const LOCALTOUR = '/localtour';
  static const BASICGOODS = '/basicgoods';
  static const INFORMATIONS = '/informations';
  static const EMBASSY = '/embassy';
  static const HOSPITALS = '/hospitals';
  static const RESTAURENTS = '/restaurents';
  static const ARTICLES = '/articles';
  static const PROFILE = '/profile';
  static const CREATEPOST = '/createpost';
  static const EDITPROFILE = '/editprofile';
  static const CHANGE_PASSWORD = '/change-password';
  static const TERMSANDCONDITIONS = '/termsandconditions';
  static const HELP = '/help';
  static const ABOUTUS = '/aboutus';
  static const LANGUAGE = '/language';
  static const SHOP = '/shop';
  static const PRODUCT_DETAILS = '/product-details';
  static const ALL_PRODUCTS = '/all-products';
  static const ALL_CATEGORIES = '/all-categories';
  static const COMMUNITY_FEED = '/community-feed';
  static const NAMAJ = '/namaj';
}
